{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikijs
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://auth.adrianmagarola.click/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.adrianmagarola.click/oauth2/start?rd=$scheme://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Email, X-Auth-Request-User"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wikijs
            port:
              number: {{ .Values.service.port }}
{{- end }}