apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    app: wikijs