apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerconfigs.monitoring.coreos.com
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: v0.74.0
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: prometheus-operator
spec:
  group: monitoring.coreos.com
  names:
    kind: AlertmanagerConfig
    listKind: AlertmanagerConfigList
    plural: alertmanagerconfigs
    singular: alertmanagerconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                route:
                  type: object
                receivers:
                  type: array
                  items:
                    type: object
                inhibitRules:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
  conversion:
    strategy: None
  preserveUnknownFields: false
