apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmonitors.monitoring.coreos.com
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: v0.74.0
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: prometheus-operator
spec:
  group: monitoring.coreos.com
  names:
    kind: PodMonitor
    listKind: PodMonitorList
    plural: podmonitors
    singular: podmonitor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                selector:
                  type: object
                namespaceSelector:
                  type: object
                podMetricsEndpoints:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
  conversion:
    strategy: None
  preserveUnknownFields: false
