apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: probes.monitoring.coreos.com
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: v0.74.0
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: prometheus-operator
spec:
  group: monitoring.coreos.com
  names:
    kind: Probe
    listKind: ProbeList
    plural: probes
    singular: probe
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targets:
                  type: object
                prober:
                  type: object
                interval:
                  type: string
                timeout:
                  type: string
      subresources:
        status: {}
  conversion:
    strategy: None
  preserveUnknownFields: false
