server:
  service:
    type: ClusterIP
  ingress:
    enabled: false
    ingressClassName: nginx
    hosts:
      - argocd.adrianmagarola.click
    paths:
      - /
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/auth-url: "https://auth.adrianmagarola.click/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.adrianmagarola.click/oauth2/start?rd=$scheme://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email"
    tls:
      - hosts:
          - argocd.adrianmagarola.click
        secretName: argocd-tls
  extraArgs:
    - --insecure

configs:
  cm:
    url: https://argocd.adrianmagarola.click
    rbac.header: X-Auth-Request-Email
    rbac.policy.default: role:none
    scopes: '[email, groups]'
    dex.config: |
      connectors:
        - type: authproxy
          id: oauth2-proxy
          name: OAuth2-Proxy-GitHub
          config:
            userHeader: X-Forwarded-User
            groupHeader: X-Forwarded-Groups
            staticGroups:
              - default
  rbac:
    policy.csv: |
      g,adrianmagarola@gmail.com,role:admin
      g,default,role:readonly
    policy.default: role:none