replicaCount: 1

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.2.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4180

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: oauth2-proxy.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

config:
  provider: github
  emailDomains:
    - *
  upstreams:
  - id: grafana
    path: /grafana
    uri: http://grafana.monitoring.svc.cluster.local:3000
  - id: argocd
    path: /argocd
    uri: http://argocd-server.argocd.svc.cluster.local:80

  cookie:
    secure: true
    httpOnly: true
    expire: 168h
    refresh: 1h
  redirect_url: https://auth.adrianmagarola.click/oauth2/callback