alertmanager:
  enabled: false  # desactiva Alertmanager si no lo necesitas

pushgateway:
  enabled: false  # desactiva Pushgateway para aligerar

server:
  enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker: "true"  # o cualquier etiqueta válida del nodo
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  persistentVolume:
    enabled: false  # sin almacenamiento persistente para desarrollo
  service:
    type: ClusterIP

  extraScrapeConfigs:
  - job_name: 'node'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: prometheus-node-exporter
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: metrics

  ## Prometheus Web UI
extraArgs:
  web.enable-lifecycle: ""  # ✅ Correcto: sin valor, solo habilita el flag


  ## Habilitar ServiceMonitor CRD compatibility (para usar con kube-prometheus-stack o Grafana)
  serviceMonitor:
    selfMonitor: true

## Prometheus node exporter (opcional)
nodeExporter:
  enabled: true

## Kube-state-metrics (opcional)
kubeStateMetrics:
  enabled: false
