prometheus:
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: v2.51.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
  resources: {}
  ingress:
    enabled: false