apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  labels:
    app: {{ .Chart.Name }}
data:
  config.cfg: |
    provider = "{{ .Values.config.provider }}"
    email_domains = [{{ .Values.config.emailDomains | join "," }}]
    upstreams = [{{ .Values.config.upstreams | join "," }}]
    cookie_secure = {{ .Values.config.cookie.secure }}
    cookie_http_only = {{ .Values.config.cookie.httpOnly }}
    cookie_expire = "{{ .Values.config.cookie.expire }}"
    cookie_refresh = "{{ .Values.config.cookie.refresh }}"
    redirect_url = "https://auth.adrianmagarola.click/oauth2/callback"