{{- range .Values.oauth2proxyInstances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-oauth2-proxy
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: {{ .replicaCount | default $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/instance: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oauth2-proxy
        app.kubernetes.io/instance: {{ .name }}
    spec:
      {{- with .nodeSelector | default $.Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .serviceAccount | default $.Values.serviceAccount }}
      {{- if .name }}
      serviceAccountName: {{ .name | default (printf "%s-oauth2-proxy" (include "oauth2-proxy.fullname" $)) }}
      {{- end }}
      {{- end }}
      containers:
        - name: oauth2-proxy
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- $instanceArgs := .args | default dict -}}
          args:
            - --http-address=0.0.0.0:4180
            - --upstream={{ .upstream }}
            - --redirect-url={{ .redirectURL }}
            - --provider={{ $instanceArgs.provider | default $.Values.defaultArgs.provider }}
            {{- range $instanceArgs.emailDomains | default $.Values.defaultArgs.emailDomains }}
            - --email-domain={{ . }}
            {{- end }}
            - --cookie-secure={{ $instanceArgs.cookieSecure | default $.Values.defaultArgs.cookieSecure | quote }}
            - --cookie-http-only={{ $instanceArgs.cookieHttpOnly | default $.Values.defaultArgs.cookieHttpOnly | quote }}
            - --cookie-expire={{ $instanceArgs.cookieExpire | default $.Values.defaultArgs.cookieExpire | quote }}
            - --cookie-refresh={{ $instanceArgs.cookieRefresh | default $.Values.defaultArgs.cookieRefresh | quote }}
            {{- if $instanceArgs.cookieDomain | default $.Values.defaultArgs.cookieDomain }}
            - --cookie-domain={{ $instanceArgs.cookieDomain | default $.Values.defaultArgs.cookieDomain }}
            {{- end }}
            - --set-xauthrequest={{ $instanceArgs.setXAuthRequest | default $.Values.defaultArgs.setXAuthRequest | quote }}
            - --pass-access-token={{ $instanceArgs.passAccessToken | default $.Values.defaultArgs.passAccessToken | quote }}
            - --pass-authorization-header={{ $instanceArgs.passAuthorizationHeader | default $.Values.defaultArgs.passAuthorizationHeader | quote }}
            {{- if $instanceArgs.sslInsecureSkipVerify | default $.Values.defaultArgs.sslInsecureSkipVerify }}
            - --ssl-insecure-skip-verify={{ $instanceArgs.sslInsecureSkipVerify | default $.Values.defaultArgs.sslInsecureSkipVerify | quote }}
            {{- end }}
            {{- range $instanceArgs.whitelistDomains | default $.Values.defaultArgs.whitelistDomains }}
            - --whitelist-domain={{ . }}
            {{- end }}
            {{- range .extraArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.existingSecretName | default (printf "%s-oauth2-credentials" .name) }}
                  key: clientID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.existingSecretName | default (printf "%s-oauth2-credentials" .name) }}
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.existingSecretName | default (printf "%s-oauth2-credentials" .name) }}
                  key: cookieSecret
          ports:
            - containerPort: 4180
              name: http
          {{- with .resources | default $.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
{{- end }}