apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oauth2-proxy
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: oauth2-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          args:
            - --provider={{ .Values.config.provider }}
            - --email-domain={{ .Values.config.emailDomains | join "," }}
            - --upstream={{ .Values.config.upstreams | join "," }}
            - --cookie-secure={{ .Values.config.cookie.secure }}
            - --cookie-http-only={{ .Values.config.cookie.httpOnly }}
            - --cookie-expire={{ .Values.config.cookie.expire }}
            - --cookie-refresh={{ .Values.config.cookie.refresh }}
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: cookie-secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oauth2-proxy
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}