apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: argocd
  labels:
    app: oauth2-proxy
type: Opaque
data:
  client-id: SXYyM2xpQ3I3NW5rOG43bVpWMnI=
  client-secret: Yzk5Y2Y0NTg3YzMwMjhmYTZkYmFhNWFhZWI4Njc1Y2IxODk5OTcxYw==
  cookie-secret: Q2hhbmdlVGhpcyBDb29raWVzU2VjcmV0