{{- range .Values.oauth2proxyInstances }}
{{- if not .credentials.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-oauth2-credentials
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
data:
  clientID: {{ (.credentials.clientId | default $.Values.defaultCredentials.clientId) | b64enc | quote }}
  clientSecret: {{ (.credentials.clientSecret | default $.Values.defaultCredentials.clientSecret) | b64enc | quote }}
  cookieSecret: {{ (.credentials.cookieSecret | default (randAlphaNum 32)) | b64enc | quote }} # Genera uno si no se provee
---
{{- end }}
{{- end }}