apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: monitoring
  labels:
    app: oauth2-proxy
type: Opaque
data:
  client-id: T3YyM2xpbnVKQkFxbmRZZE5MMDk=
  client-secret: OTA5M2YwMTVmYjNmOTlmMjcwMGExYWQ0N2E5NTYwNGFjMmQwNWM1NA==
  cookie-secret: Q2hhbmdlVGhpcyBDb29raWVzU2VjcmV0