{{- range .Values.oauth2proxyInstances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-oauth2-proxy
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: ClusterIP # Or LoadBalancer, NodePort as needed, but ClusterIP is typical for internal proxy
  ports:
    - port: 4180
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .name }}
---
{{- end }}