replicaCount: 1
image:
  repository: requarks/wiki
  tag: 2.5
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources: {}
ingress:
  enabled: false
  host: wikijs.adrianmagarola.click