{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "intranet.fullname" . }}-pvc"
  labels:
    {{- include "intranet.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
