apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: prometheus-operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.operator.name }}
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      containers:
        - name: prometheus-operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          args:
{{ toYaml .Values.operator.args | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.operator.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.operator.resources | indent 12 }}
