apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.coreos.com
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: v0.74.0
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: prometheus-operator
spec:
  group: monitoring.coreos.com
  names:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    singular: prometheus
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                version:
                  type: string
                image:
                  type: string
                nodeSelector:
                  type: object
                resources:
                  type: object
                affinity:
                  type: object
                tolerations:
                  type: array
                  items:
                    type: object
                serviceAccountName:
                  type: string
                serviceMonitorSelector:
                  type: object
                podMonitorSelector:
                  type: object
                ruleSelector:
                  type: object
                storage:
                  type: object
      subresources:
        status: {}
  conversion:
    strategy: None
  preserveUnknownFields: false
