apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.operator.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: prometheus-operator  
spec:
  type: {{ .Values.operator.service.type }}
  ports:
{{ toYaml .Values.operator.service.ports | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ .Values.operator.name }}
