ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
    nodeSelector:
      node-role.k3s.io/master: "true"
    ingressClassResource:
      name: nginx
      controllerValue: k8s.io/ingress-nginx
    ingressClassByName: true
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false
