services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE:      /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password

  wp:
    build: .
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress

      WP_SITE_URL:   http://localhost:8080
      WP_SITE_TITLE: "Mi Intranet"
      WP_ADMIN_USER: admin
      WP_ADMIN_EMAIL: admin@example.com
    ports:
      - "8080:80"
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
    secrets:
      - db_password
      - wp_admin_pass


volumes:
  db_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_pass:
    file: ./secrets/wp_admin_pass.txt
