auth:
  rootPassword: rootpassword
  database: bitnami_wordpress
  username: bn_wordpress
  password: wordpresspass

primary:
  persistence:
    enabled: true
    size: 8Gi

service:
  type: ClusterIP

