replicaCount: 1
image:
  repository: grafana/grafana
  tag: 8.0.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources: {}
ingress:
  enabled: true
nodeSelector:
  node-role.kubernetes.io/worker: true
prometheus:
  replicaCount: 1
  image:
    repository: "prom/prometheus"
    tag: "latest"
persistence:
  enabled: true
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 5Gi