auth:
  rootPassword: rootpassword
  database: intranet_db # Changed from bitnami_wordpress
  username: bn_intranet # Changed from bn_wordpress
  password: intranetpass # Changed from wordpresspass

primary:
  persistence:
    enabled: true
    size: 8Gi

# service: # This service section might be for MariaDB itself, ensure it's intended.
#   type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 1001

containerSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

