apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amagarola/proyecto_intranet.git
    targetRevision: HEAD
    path: charts/wikijs
    helm:
      valueFiles:
        - values.yaml  # Asegúrate de que exista en esa carpeta o cámbialo según corresponda
  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true