apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intranet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amagarola/proyecto_intranet.git
    targetRevision: main
    path: charts/intranet
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
