{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "wordpress-custom.fullname" . }}"
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: "{{ .Values.ingress.className }}"
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.ingress.hostname }}"
      secretName: "{{ include "wordpress-custom.fullname" . }}-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ include "wordpress-custom.fullname" . }}"
                port:
                  number: 80
{{- end }}
