name: Install LetsEncrypt Issuer

on:
  workflow_dispatch:

jobs:
  install-letsencrypt-issuer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG" > kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Install letsencrypt-issuer chart
        run: |
          helm upgrade --install letsencrypt-issuer ./charts/letsencrypt-issuer \
            --namespace cert-manager \
            --create-namespace \
            --set email=adrianmagarola@gmail.com \
            --set ingressClass=nginx
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
