name: Deploy Applications

on:
  workflow_dispatch:
    inputs:
      applications:
        description: "Select applications to deploy"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - oauth2-proxy
          - wikijs
          - prometheus
          - grafana

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG" > kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Deploy Applications
        run: |
          if [ "${{ inputs.applications }}" = "all" ]; then
            echo "Deploying all applications..."
            kubectl apply -f apps/
          else
            echo "Deploying selected application: ${{ inputs.applications }}"
            kubectl apply -f apps/app-${{ inputs.applications }}.yaml
          fi
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig