name: Deploy ArgoCD

on:
  workflow_dispatch:

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG" > kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm Repositories
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Deploy ArgoCD
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --version 5.55.0 \
            -f terraform/modules/helm-releases/argocd-values.yaml \
            --set configs.secret.githubClientSecret=${{ secrets.GH_CLIENT_SECRET }} \
            --wait
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig