name: 🚀🛑 Iniciar/Detener Todas las Instancias EC2
run-name: ${{ format('{0} Todas las Instancias EC2', github.event.inputs.ACTION == 'start' && '🚀 Iniciar' || '🛑 Parar') }}

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: 'Acción a realizar (iniciar o detener)'
        required: true
        type: choice
        options:
          - start
          - stop

jobs:
  ec2-control:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Iniciar o detener todas las instancias EC2
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --output text)
          if [ -z "$INSTANCE_IDS" ]; then
            echo "No se encontraron instancias EC2."
            exit 0
          fi
          if [ "${{ github.event.inputs.ACTION }}" = "start" ]; then
            aws ec2 start-instances --instance-ids $INSTANCE_IDS
          elif [ "${{ github.event.inputs.ACTION }}" = "stop" ]; then
            aws ec2 stop-instances --instance-ids $INSTANCE_IDS
          else
            echo "Acción inválida: ${{ github.event.inputs.ACTION }}" >&2
            exit 1
          fi

      - name: Iniciar o detener el Auto Scaling Group de workers
        run: |
          ASG_NAME="k3s-workers-asg"
          if [ "${{ github.event.inputs.ACTION }}" = "start" ]; then
            aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --min-size 1 --max-size 3 --desired-capacity 1
            echo "ASG $ASG_NAME iniciado (min=1, max=3, desired=1)"
          elif [ "${{ github.event.inputs.ACTION }}" = "stop" ]; then
            aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --min-size 0 --max-size 0 --desired-capacity 0
            echo "ASG $ASG_NAME detenido (min=0, max=0, desired=0)"
          else
            echo "Acción inválida: ${{ github.event.inputs.ACTION }}" >&2
            exit 1
          fi
